#!/bin/bash

clear

if [ -f OK.txt ]; then :; else echo -e "$(printf '=%.0s' {1..19})\n IPs CloudFlare|ON\n$(printf '=%.0s' {1..19})" >> OK.txt; fi

echo -e "\e[01;33mATENÇÃO FERRAMENTA APENAS PARA PROFISSIONAIS \e[0m☠\n\n\e[02mEssa ferramenta irá verificar se o\nHOST utiliza proxy/CDN(CloudFlare)\nutilize com INTERNET!\n\n*HOST não é seu domínio barboleta\n*Ex: vivo.com.br ou tigo.com.sv etc\e[0m\n"

data=$(curl -s https://subdomainfinder.c99.nl/index.php --compressed | pup 'input' | grep hidden | cut -d '"' -f4,6)
 data2=$(($(wc -l <<< "$data")-2))
  data3=$(head -n "$data2" <<< "$data" | tr -s "\n" "&" | tr -s '"' '=' | sed -r 's/.$//g')
path=$(curl -s https://subdomainfinder.c99.nl/js/nginx_v37728122119.js | cut -d '"' -f2)
 path2=$(curl -s https://subdomainfinder.c99.nl/js/nginx_v37728122119.js | cut -d '(' -f11 | cut -d ' ' -f4 | cut -d '.' -f2)
  path3=$(curl -s https://subdomainfinder.c99.nl$path | grep "$path2.........." -o | cut -d ':' -f2 | cut -d ',' -f1)
quant=$(($(grep "&" -o <<< "$data3" | wc -l)+1))
csrf=$(cut -d '&' -f$quant <<< "$data3" | cut -d '=' -f1)
 csrf2=$(<csrf)
ok=$(eval "sed \"s/$csrf/$csrf2/\" <<< \"$data3\"")

echo -e "\e[01;37m Coloque o HOST para verificação\e[0m"
read -p "Host: " HOST

OK=$(curl -s https://subdomainfinder.c99.nl/index.php -H "content-type: application/x-www-form-urlencoded" -H "origin: https://subdomainfinder.c99.nl" -H "referer: https://subdomainfinder.c99.nl/index.php" -H "user-agent: Android" -d "$ok&jn=JS+aan%2C+T+aangeroepen%2C+CSRF+aangepast&domain=$HOST&lol-stop-reverse-engineering-my-source-and-buy-an-api-key=60ade41f4d4e5a01562f2baf8e8058b9038af54d&scan_subdomains=" --compressed | pup 'tbody')

ok2=$(cat -n <<< "$OK" | grep "CloudFlare is" | awk '{$1=$1};1' | cut -d ' ' -f1)
linhas=$(wc -l <<< "$ok2")
echo
for i in $(seq "$linhas"); do
      q=$(sed -n "$i"p <<< "$ok2")
      w=$(sed -n "$q"p <<< "$OK" | egrep 'on|off' -o | head -n1)
       case $w in 
            on)
               a=$(($(sed -n "$i"p <<< "$ok2")-4))
               b=$(sed -n "$a"p <<< "$OK" | tr -d ' ')
               echo -e "\e[07;01;32;40m CloudFlare|ON \e[0m - \e[01;37m$b \e[0m"; sleep 2
               echo -e "$b" >> OK.txt
               ;;
          off)
               a2=$(($(sed -n "$i"p <<< "$ok2")-4))
               b2=$(sed -n "$a2"p <<< "$OK" | tr -d ' ')
                 case $b2 in
                      none);;
                      *) echo -e "\e[01;37m CloudFlare|OFF\e[0m\e[02m - $b2 \e[0m"
                 esac
     esac
done; echo -e "$HOST" >> OK.txt; echo $(printf '=%.0s' {1..19}) >> OK.txt
